### ISSUE TITLE
Searchability

### ISSUE THREAD

**Issue by localleon** [jcartw/google-your-smart-thing#1]
Hello @jcartw89, 

this is a great project and has just ended my endless search for a working Google Actions Sample Project. 

But it is quite hard to find this project. Maybe you could add some tags to your Github Repo (google-actions, google-smart-home, smart-home) so more people can find it. 

You should also link your Medium.com Article in the README or somewhere else (website of repo?). 

Thanks for your work!

**Comment by jcartw** [comment]
Thanks for the feedback! I've added some topics to help out with discovery.
